name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Add this section to set up JDK 8
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    # Add this section to build your application
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    # (Your existing steps, like installing dependencies or running tests, go here)
